---
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /etc/directory
    state: directory
    mode: '0755'
- name: Check date
  ansible.builtin.command: "date > /etc/directory/date.file"

